name: CI_Release

on: push

jobs:
  build-mac:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/ADB_Assistant_${{ github.ref }}
        asset_name: ADB_Assistant_${{ github.ref }}
        tag: ${{ github.ref }}
        overwrite: true
